#!/usr/bin/env python3
"""Generate docs/ROUTES.md from the live GoogleModule subclasses.

This script is the single source of truth for route tables. It discovers
modules via gatekeeper.modules.AVAILABLE_MODULES, imports each Module class,
calls get_routes(), and emits a Markdown reference document.

Usage:
    python scripts/generate_routes_doc.py [--out docs/ROUTES.md]

Exit codes:
    0 - success
    1 - module load failure
    2 - template render failure
    3 - write failure
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from gatekeeper.modules import AVAILABLE_MODULES, load_module


def _get_commit_sha() -> str:
    """Return the current git commit SHA, or 'unknown' if not in a git repo."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def _url_from_route_id(module_name: str, route_id: str) -> str:
    """Convert a route_id to its REST URL path."""
    parts = route_id.split(".", 1)
    if len(parts) > 1:
        return f"/api/v1/{module_name}/{parts[1].replace('.', '/')}"
    return f"/api/v1/{module_name}/{parts[0]}"


def _route_block(route, module_name: str) -> str:
    """Render one route's detailed Markdown block."""
    url = _url_from_route_id(module_name, route.route_id)
    lines: list[str] = []
    lines.append(f"#### `{route.route_id}`")
    lines.append("")
    lines.append(f"- **Method:** `{route.method}`")
    lines.append(f"- **URL:** `{url}`")
    lines.append(f"- **Google path:** `{route.google_path}`")
    if route.base_url:
        lines.append(f"- **Base URL:** `{route.base_url}`")
    if route.query_params:
        lines.append(f"- **Query params:** {', '.join(f'`{p}`' for p in route.query_params)}")
    if route.binary_response:
        lines.append("- **Binary response:** `True`")
    if route.multipart_upload:
        lines.append("- **Multipart upload:** `True`")
    lines.append(f"- **Enabled by default:** `{'Yes' if route.enabled_by_default else 'No'}`")
    if route.default_policy:
        lines.append(f"- **Default policy:** `{json.dumps(route.default_policy, sort_keys=True)}`")
    lines.append("")
    lines.append(route.description or "")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(route.input_schema, indent=2, sort_keys=True))
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def generate() -> str:
    """Build the full Markdown document."""
    lines: list[str] = []
    lines.append("# Gatekeeper Route Reference")
    lines.append("")
    lines.append(
        "This document is auto-generated by `scripts/generate_routes_doc.py` from the live "
        "`GoogleModule` subclasses. Do not edit by hand."
    )
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Module | Display name | Routes | Default-enabled | Required OAuth scopes |")
    lines.append("|---|---|---:|---:|---|")

    module_data: list[tuple] = []
    total_routes = 0
    total_enabled = 0

    for module_name in sorted(AVAILABLE_MODULES.keys()):
        mod = load_module(module_name)
        if mod is None:
            print(f"Failed to load module: {module_name}", file=sys.stderr)
            sys.exit(1)

        routes = mod.get_routes()
        enabled_count = sum(1 for r in routes if r.enabled_by_default)
        total_routes += len(routes)
        total_enabled += enabled_count
        scopes_md = "<br>".join(f"`{s}`" for s in mod.required_scopes)
        module_data.append((module_name, mod, routes))
        lines.append(
            f"| `{module_name}` | {mod.display_name} | {len(routes)} | {enabled_count} | {scopes_md} |"
        )

    lines.append("")
    lines.append(f"**Total routes:** {total_routes}  ")
    lines.append(f"**Default-enabled routes:** {total_enabled}")
    lines.append("")

    # Per-module deep dives
    for module_name, mod, routes in module_data:
        lines.append(f"## Module: `{module_name}` — {mod.display_name}")
        lines.append("")
        lines.append(mod.description or "")
        lines.append("")
        lines.append("### Required OAuth scopes")
        lines.append("")
        for scope in mod.required_scopes:
            lines.append(f"- `{scope}`")
        lines.append("")
        lines.append(f"### Routes ({len(routes)})")
        lines.append("")
        for route in routes:
            lines.append(_route_block(route, module_name))

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(f"Generated at: `{datetime.now(UTC).isoformat()}Z`")
    lines.append(f"Source commit: `{_get_commit_sha()}`")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Gatekeeper route documentation")
    parser.add_argument(
        "--out",
        type=Path,
        default=PROJECT_ROOT / "docs" / "ROUTES.md",
        help="Output path (default: docs/ROUTES.md)",
    )
    args = parser.parse_args()

    try:
        content = generate()
    except Exception as exc:
        print(f"Render failure: {exc}", file=sys.stderr)
        return 2

    try:
        args.out.write_text(content, encoding="utf-8")
    except Exception as exc:
        print(f"Write failure: {exc}", file=sys.stderr)
        return 3

    print(f"Generated {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
